### ISSUE TITLE
Can't get bundle to work with SonataAdmin

### ISSUE THREAD

**Issue by cured** [matteosister/TranslationBundle#1]
Hi. When trying to integrate your bundle and my entity with SonataAdmin get such error
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Notice: Undefined index: translations in vendor\doctrine\lib\Doctrine\ORM\UnitOfWork.php line 2123") in SonataAdminBundle::standard_layout.html.twig at line 15.

here is the gist
https://gist.github.com/3313922#

**Comment by matteosister** [comment]
which version of symfony are you using?

**Comment by cured** [comment]
2.0.15

**Comment by matteosister** [comment]
the problem could be the fact that you removed the index name in the MenuTranslations entity.
Check the readme....
Could you please put this in your MenuTranslations entity, before the class name (the change is in **@ORM\UniqueConstraint**):

``` php
<?php
/**
 * @ORM\Entity
 * @ORM\Table(name="menu_translations",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="menu_translations_unique_idx", columns={
 *         "locale", "object_id", "field"
 *     })}
 * )
 */
class MenuTranslations extends TranslationEntity
```

Then do a

``` bash
$ ./app/console doctrine:schema:update --force
```

and check if everything works.

With your mappings I wasn't able to update the schema...

**Comment by cured** [comment]
first thanks for your help.
well, i've read the readme and followed instructions written there
however can't get this to work

then i walk through the tests in your bundle
there i didn't find mention of the index name
so i try this way and no result

by the way doctrine:schema:update --force works with my mappings

maybe the case is that i added 
    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    CypressTranslationBundle: ~

i don't know actually if this influences at all

maybe you have full written application not only the bundle
so i can dig into the code and find what i'm doing wrong

**Comment by matteosister** [comment]
I was able to reproduce the problem...investigating now...

**Comment by matteosister** [comment]
ok, the problem is the metadata listener of doctrine, that create the relation with the translation entity without the needs to specify manually the property. Now doing this is not easy, and maybe there are also different ways based on the doctrine version you are using.

So.
I decided that it's far better to remove the "magic" and define the "translations" property by hand on the class. A little bit of work that remove many problems.

I've tested with the SonataAdminBundle, and your setup, and it works. Please take a look at the updated readme.

Many thanks for taking time in reporting this issue.
Let me know if it is now ok for you.

As a side note _auto_mapping: true_ should make the _mappings_ configuration useless, because afaik it tells doctrine to look inside every bundle.

**Comment by cured** [comment]
thank you  very much
everything works like a charm
you saved my time :)

**Comment by matteosister** [comment]
You're welcome! Thanks to you for reporting the issue.
